# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-14 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='addedDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
